title: Relm Developer Portal
description: Developer documentation portal
theme: just-the-docs

url: https://xbasedigital.github.io/docs
logo: "/assets/relm.png"

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

heading_anchors: true
color_scheme: dark

footer_content: "Copyright &copy; 2025 Relm"

callouts:
  endpoint-desc:
    title: Endpoint Description
    color: blue
